apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  # type: NodePort
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80

# This will create a clusterIP, only accessible from inside the cluster, you can test this by finding the IP address (kubectl get svc), then running a busybox container:
# kubectl run -i --tty --rm debug --image=busybox --restart=Never -- sh
# Or, set spec.type to NodePort to make this a nodeport
