apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>My Custom Page4</title></head>
    <body><h1>Hello from ConfigMap!</h1></body>
    </html>
