apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: rbac-demo
---
# create a role to list and get pods only
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rbac-demo
  name: pod-read-only
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
# bind the role to the serviceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: rbac-demo
subjects:
- kind: ServiceAccount
  name: pod-reader
  namespace: rbac-demo
roleRef:
  kind: Role
  name: pod-read-only
  apiGroup: rbac.authorization.k8s.io
---
# Example pod for testing
apiVersion: v1
kind: Pod
metadata:
  name: demo-nginx
  namespace: rbac-demo
spec:
  containers:
  - name: nginx
    image: nginx
---
# Example service attached to the pod
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: rbac-demo
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
